// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CucumberTesting.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TaggingNotesFeature : object, Xunit.IClassFixture<TaggingNotesFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Tagging Notes", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "NoteServiceTagMethod.feature"
#line hidden
        
        public TaggingNotesFeature(TaggingNotesFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Both title and content empty")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Both title and content empty")]
        public async System.Threading.Tasks.Task BothTitleAndContentEmpty()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Both title and content empty", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
        await testRunner.GivenAsync("a note with the title \"\" and the content \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table1.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table1.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table1.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 7
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table1, "And ");
#line hidden
#line 12
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            ""});
#line 13
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table2, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Both title and content whitespace")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Both title and content whitespace")]
        public async System.Threading.Tasks.Task BothTitleAndContentWhitespace()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Both title and content whitespace", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
        await testRunner.GivenAsync("a note with the title \" \" and the content \"  \"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table3.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table3.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table3.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 20
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table3, "And ");
#line hidden
#line 25
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            ""});
#line 26
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table4, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Both title and content null")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Both title and content null")]
        public async System.Threading.Tasks.Task BothTitleAndContentNull()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Both title and content null", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 32
        await testRunner.GivenAsync("a note with the title null and the content null", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table5.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table5.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table5.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 33
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table5, "And ");
#line hidden
#line 38
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            ""});
#line 39
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table6, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Title empty, content with keyword")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Title empty, content with keyword")]
        public async System.Threading.Tasks.Task TitleEmptyContentWithKeyword()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Title empty, content with keyword", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
        await testRunner.GivenAsync("a note with the title \"\" and the content \"This is a task\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table7.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table7.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table7.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 46
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table7, "And ");
#line hidden
#line 51
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "Tags"});
                table8.AddRow(new string[] {
                            "Task"});
#line 52
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table8, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Title null, content with keywords")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Title null, content with keywords")]
        public async System.Threading.Tasks.Task TitleNullContentWithKeywords()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Title null, content with keywords", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
        await testRunner.GivenAsync("a note with the title null and the content \"Important meeting\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table9.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table9.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table9.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 60
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table9, "And ");
#line hidden
#line 65
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "Tags"});
                table10.AddRow(new string[] {
                            "Urgent"});
                table10.AddRow(new string[] {
                            "Meeting"});
#line 66
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table10, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Content empty, title with keywords")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Content empty, title with keywords")]
        public async System.Threading.Tasks.Task ContentEmptyTitleWithKeywords()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Content empty, title with keywords", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 73
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 74
        await testRunner.GivenAsync("a note with the title \"Urgent task\" and the content \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table11.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table11.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table11.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 75
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table11, "And ");
#line hidden
#line 80
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "Tags"});
                table12.AddRow(new string[] {
                            "Task"});
#line 81
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table12, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Content null, title with keyword")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Content null, title with keyword")]
        public async System.Threading.Tasks.Task ContentNullTitleWithKeyword()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Content null, title with keyword", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 87
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 88
        await testRunner.GivenAsync("a note with the title \"Meeting notes\" and the content null", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table13.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table13.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table13.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 89
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table13, "And ");
#line hidden
#line 94
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "Tags"});
                table14.AddRow(new string[] {
                            "Meeting"});
#line 95
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table14, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Both with same keywords")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Both with same keywords")]
        public async System.Threading.Tasks.Task BothWithSameKeywords()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Both with same keywords", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 101
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 102
        await testRunner.GivenAsync("a note with the title \"Urgent task\" and the content \"This is a task\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table15.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table15.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table15.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 103
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table15, "And ");
#line hidden
#line 108
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "Tags"});
                table16.AddRow(new string[] {
                            "Task"});
#line 109
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table16, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Both with different keywords for same tag")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Both with different keywords for same tag")]
        public async System.Threading.Tasks.Task BothWithDifferentKeywordsForSameTag()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Both with different keywords for same tag", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 115
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 116
        await testRunner.GivenAsync("a note with the title \"Meeting notes\" and the content \"Discuss and review\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table17.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table17.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table17.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 117
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table17, "And ");
#line hidden
#line 122
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "Tags"});
                table18.AddRow(new string[] {
                            "Meeting"});
#line 123
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table18, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Both with different keywords for different tags")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Both with different keywords for different tags")]
        public async System.Threading.Tasks.Task BothWithDifferentKeywordsForDifferentTags()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Both with different keywords for different tags", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 129
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 130
        await testRunner.GivenAsync("a note with the title \"Urgent meeting\" and the content \"This is a task\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table19.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table19.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table19.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 131
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table19, "And ");
#line hidden
#line 136
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "Tags"});
                table20.AddRow(new string[] {
                            "Task"});
                table20.AddRow(new string[] {
                            "Meeting"});
#line 137
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table20, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Content with keyword, title without")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Content with keyword, title without")]
        public async System.Threading.Tasks.Task ContentWithKeywordTitleWithout()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Content with keyword, title without", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 144
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 145
        await testRunner.GivenAsync("a note with the title \"Grocery Shopping\" and the content \"Buy milk, eggs, and bre" +
                        "ad\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table21.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table21.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table21.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 146
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table21, "And ");
#line hidden
#line 151
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            ""});
#line 152
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table22, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Both with keywords for different tags")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Both with keywords for different tags")]
        public async System.Threading.Tasks.Task BothWithKeywordsForDifferentTags()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Both with keywords for different tags", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 157
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 158
        await testRunner.GivenAsync("a note with the title \"Team Meeting\" and the content \"Discuss progress and review" +
                        " tasks\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table23.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table23.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table23.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 159
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table23, "And ");
#line hidden
#line 164
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "Tags"});
                table24.AddRow(new string[] {
                            "Task"});
                table24.AddRow(new string[] {
                            "Meeting"});
#line 165
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table24, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="No keywords in title or content")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "No keywords in title or content")]
        public async System.Threading.Tasks.Task NoKeywordsInTitleOrContent()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("No keywords in title or content", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 172
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 173
        await testRunner.GivenAsync("a note with the title \"Vacation Photos\" and the content \"Pictures from my trip to" +
                        " Hawaii\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table25.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table25.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table25.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 174
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table25, "And ");
#line hidden
#line 179
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            ""});
#line 180
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table26, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Case-insensitive keyword matching")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Case-insensitive keyword matching")]
        public async System.Threading.Tasks.Task Case_InsensitiveKeywordMatching()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Case-insensitive keyword matching", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 185
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 186
        await testRunner.GivenAsync("a note with the title \"This is a TASK\" and the content \"Very IMPORTANT indeed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table27.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table27.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table27.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 187
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table27, "And ");
#line hidden
#line 192
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "Tags"});
                table28.AddRow(new string[] {
                            "Task"});
                table28.AddRow(new string[] {
                            "Urgent"});
#line 193
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table28, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Mixed case keywords")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Mixed case keywords")]
        public async System.Threading.Tasks.Task MixedCaseKeywords()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mixed case keywords", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 200
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 201
        await testRunner.GivenAsync("a note with the title \"urgent TASK\" and the content \"ASAP work\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table29.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table29.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table29.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 202
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table29, "And ");
#line hidden
#line 207
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "Tags"});
                table30.AddRow(new string[] {
                            "Task"});
                table30.AddRow(new string[] {
                            "Urgent"});
#line 208
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table30, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Synonym keywords")]
        [Xunit.TraitAttribute("FeatureTitle", "Tagging Notes")]
        [Xunit.TraitAttribute("Description", "Synonym keywords")]
        public async System.Threading.Tasks.Task SynonymKeywords()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Synonym keywords", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 215
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 216
        await testRunner.GivenAsync("a note with the title \"Review meeting\" and the content \"Discuss project\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Keywords"});
                table31.AddRow(new string[] {
                            "Task",
                            "todo, task, work"});
                table31.AddRow(new string[] {
                            "Urgent",
                            "important, asap"});
                table31.AddRow(new string[] {
                            "Meeting",
                            "meeting, discuss, review"});
#line 217
        await testRunner.AndAsync("the following tags exist in the repository:", ((string)(null)), table31, "And ");
#line hidden
#line 222
        await testRunner.WhenAsync("the note is tagged", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                            "Tags"});
                table32.AddRow(new string[] {
                            "Meeting"});
#line 223
        await testRunner.ThenAsync("the note should have the following tags:", ((string)(null)), table32, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await TaggingNotesFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await TaggingNotesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
