services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
      
# TODO: Create an actual docker compose file that will run the api and the database, so it builds the BACKEND
# Then, create a docker compose file that will run the frontend and backend together, so it builds the FULLSTACK